### ISSUE TITLE
Sharing takes me to network page, opens post editor but no text inside

### ISSUE THREAD

**Issue by strk** [Leberwurscht/post2friendica#1]
There's just a blank text area when I click on "share to friendica" on the friendica side.
Version 3.4.0 running there.

**Comment by strk** [comment]
anyone alive here ?

**Comment by ghost** [comment]
Doesn'seem like...

**Comment by strk** [comment]
Well it finally worked, I really had to enable the visual editor, and then wait a few tens of seconds for the text to arrive...
